# This file was generated by the {rix} R package v0.18.2 on 2026-05-19
# with following call:
# >rix(date = "2026-01-14",
#  > r_pkgs = c("tidyr",
#  > "dplyr",
#  > "ggplot2",
#  > "languageserver"),
#  > system_pkgs = NULL,
#  > git_pkgs = NULL,
#  > tex_pkgs = NULL,
#  > py_conf = list(py_version = "3.13",
#  > py_pkgs = c("polars",
#  > "scikit-learn")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-01-14.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2
      languageserver
      tidyr;
  };
   
 
  pyconf = builtins.attrValues {
    inherit (pkgs.python313Packages) 
      pip
      ipykernel
      polars
      scikit-learn;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      glibcLocales
      nix
      python313;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python313}/bin/python";

    buildInputs = [ rpkgs pyconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
