# This file was generated by the {rix} R package v0.18.2 on 2026-05-19
# with following call:
# >rix(date = "2026-04-30",
#  > r_pkgs = c("dplyr",
#  > "ggdag",
#  > "igraph",
#  > "quarto",
#  > "reticulate",
#  > "rix",
#  > "visNetwork"),
#  > git_pkgs = list(list(package_name = "rixpress",
#  > repo_url = "https://github.com/ropensci/rixpress",
#  > commit = "4993b387c777152f51d9587c3e90e905bb64e1ce")),
#  > py_conf = list(py_version = "3.14",
#  > py_pkgs = c("polars")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.6.0")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-04-30.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggdag
      igraph
      quarto
      reticulate
      rix
      visNetwork;
  };
 
    rixpress = (pkgs.rPackages.buildRPackage {
      name = "rixpress";
      src = pkgs.fetchgit {
        url = "https://github.com/ropensci/rixpress";
        rev = "4993b387c777152f51d9587c3e90e905bb64e1ce";
        sha256 = "sha256-YDSQyCqDx9yeqWURMk/YRXS4sm3FnSCyj7EeF/zwyEs=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          cli
          igraph
          jsonlite
          processx;
      };
    });
   
 
  pyconf = builtins.attrValues {
    inherit (pkgs.python314Packages) 
      pip
      ipykernel
      polars;
  };
   
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      glibcLocales
      nix
      python314
      quarto
      which
      pandoc;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    RETICULATE_PYTHON = "${pkgs.python314}/bin/python";

    buildInputs = [ rixpress rpkgs pyconf system_packages ];
    
  }; 
in
  {
    inherit pkgs shell;
  }
